version: '3.8'

services:

  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sales
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  adminer:
    container_name: pgadmin_container
    image: adminer
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8080:8080
      
  python_script:
    container_name: python_script_container
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./sales_data.csv:/app/sales_data.csv
      - ./etl.py:/app/etl.py